# Generated by Django 5.2.8 on 2025-12-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("RENT", "Rent")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("APARTMENT", "Apartment"),
                            ("VILLA", "Villa"),
                            ("LAND", "Land"),
                            ("STUDIO", "Studio"),
                            ("OFFICE", "Office"),
                            ("SHOP", "Shop"),
                            ("WAREHOUSE", "Warehouse"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "rent_unit",
                    models.CharField(
                        blank=True,
                        choices=[("MONTH", "Month"), ("DAY", "Day"), ("YEAR", "Year")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("address", models.TextField()),
                ("area", models.IntegerField()),
                ("bedrooms", models.IntegerField()),
                ("bathrooms", models.IntegerField()),
                ("floors", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("INACTIVE", "Inactive"),
                            ("RENTED", "Rented"),
                            ("APPROVED_AND_PENDING", "Approved and Pending"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=25,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("PARTIAL", "Partial"),
                            ("VERIFIED", "Verified"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "rental_status",
                    models.CharField(
                        choices=[("AVAILABLE", "Available"), ("RENTED", "Rented")],
                        default="AVAILABLE",
                        max_length=10,
                    ),
                ),
                ("available_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ListingDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("IDENTITY", "Identity"),
                            ("OWNERSHIP", "Ownership"),
                            ("ASSURANCE", "Assurance"),
                            ("REGISTER", "Register"),
                            ("SILBIYA", "Silbiya"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="listings/documents/")),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("APPROVED", "Approved"), ("REJECTED", "Rejected")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("admin_note", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="listings/images/")),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
