# Generated by Django 5.2.8 on 2025-12-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listingdocument",
            name="owner_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="listingdocument",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("PENDING", "Pending"),
                ],
                default="PENDING",
                max_length=10,
                null=True,
            ),
        ),
    ]
