# Generated by Copilot on 2025-12-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="document_notes",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
