# Generated by Copilot on 2025-12-26

from django.db import migrations
from django.utils.crypto import get_random_string
from django.utils.text import slugify


def backfill_listing_slugs(apps, schema_editor):
    Listing = apps.get_model("listings", "Listing")

    qs = Listing.objects.filter(slug__isnull=True) | Listing.objects.filter(slug="")
    for listing in qs.iterator():
        base_slug = slugify(getattr(listing, "title", "") or "") or "listing"
        candidate = base_slug
        while Listing.objects.exclude(pk=listing.pk).filter(slug=candidate).exists():
            candidate = f"{base_slug}-{get_random_string(6)}"
        listing.slug = candidate
        listing.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_listing_document_notes"),
    ]

    operations = [
        migrations.RunPython(backfill_listing_slugs, migrations.RunPython.noop),
    ]
