# Generated by Django 5.2.8 on 2025-12-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listingdocument_owner_note_and_more'),
        ('listings', '0004_backfill_listing_slugs'),
    ]

    operations = [
    ]
