# Generated by Copilot on 2025-12-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_merge_20251228_1631"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listingdocument",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="listings/documents/"),
        ),
    ]
