export const wilayas = [
  "Adrar",
  "Chlef",
  "Laghouat",
  "Oum El Bouaghi",
  "Batna",
  "Béjaïa",
  "Biskra",
  "Béchar",
  "Blida",
  "Bouira",
  "Tamanrasset",
  "Tébessa",
  "Tlemcen",
  "Tiaret",
  "Tizi Ouzou",
  "Algiers",
  "Djelfa",
  "Jijel",
  "Sétif",
  "Saïda",
  "Skikda",
  "Sidi Bel Abbès",
  "Annaba",
  "Guelma",
  "Constantine",
  "Médéa",
  "Mostaganem",
  "M’Sila",
  "Mascara",
  "Ouargla",
  "Oran",
  "El Bayadh",
  "Illizi",
  "Bordj Bou Arreridj",
  "Boumerdès",
  "El Tarf",
  "Tindouf",
  "Tissemsilt",
  "El Oued",
  "Khenchela",
  "Souk Ahras",
  "Tipaza",
  "Mila",
  "Aïn Defla",
  "Naama",
  "Aïn Témouchent",
  "Ghardaïa",
  "Relizane",
  "Timimoun",
  "Bordj Badji Mokhtar",
  "Ouled Djellal",
  "Béni Abbès",
  "In Salah",
  "In Guezzam",
  "Touggourt",
  "Djanet",
  "El M'Ghair",
  "El Meniaa"
];


export const regions = {
  "Adrar": ["Adrar",
            "Akabli",
            "Aoulef",
            "Bouda",
            "Charouine",
            "Deldoul",
            "Fenoughil",
            "In Zghmir",
            "Metarfa",
            "Ouled Ahmed Tammi",
            "Reggane",
            "Sali",
            "Sebaa",
            "Tamantit",
            "Tamekten",
            "Tamest",
            "Tit",
            "Tsabit",
            "Zaouiet Kounta"],

  "Chlef": ["Chlef",
          "Tenes",
          "Abou El Hassan",
          "Boukadir",
          "El Karimia",
          "Oued Fodda",
          "Bouzeghaia",
          "Ouled Abbes",
          "Ouled Fares",
          "Oum Drou",
          "Beni Bouateb",
          "Sidi Akkacha",
          "Sidi Abderrahmane",
          "Labiod Medjadja",
          "Taougrit",
          "El Marsa",
          "Aïn Merane",
          "Zeboudja",
          "Herenfa",
          "Sendjas",
          "Chorfa",
          "Beni Rached",
          "El Hadjadj"],

  "Laghouat": ["Laghouat",
              "Ain Madhi",
              "Tadjemout",
              "Ksar El Hirane",
              "Sidi Makhlouf",
              "Hassi Delaa",
              "Hassi R'Mel",
              "El Assafia",
              "Aflou",
              "Brida",
              "El Ghicha",
              "Gueltat Sidi Saad",
              "Tadjrouna",
              "Oued Morra",
              "Oued M'zi",
              "Beni Mekhlouf",
              "Sebgag",
              "Sidi Bouzid",
              "Sidi Boumour",
              "Taouiala"],

  "Oum El Bouaghi":["Oum El Bouaghi",
                    "Aïn Beida",
                    "Aïn M'Lila",
                    "Aïn Babouche",
                    "Aïn Diss",
                    "Aïn Fakroun",
                    "Aïn Kercha",
                    "Behir Chergui",
                    "Bir Chouhada",
                    "Dhalaa",
                    "El Amiria",
                    "El Belala",
                    "El Djazia",
                    "El Fedjouz Boughrara Saoudi",
                    "Fkirina",
                    "Ksar Sbahi",
                    "Ouled Gacem",
                    "Ouled Hamla",
                    "Ouled Zouai",
                    "Rahia",
                    "Sigus",
                    "Soukrine",
                    "Zorg",
                    "Hamadi Ksar"],

  "Batna":["Batna",
          "Arris",
          "Barika",
          "Boumagueur",
          "Bouzina",
          "Chaïba",
          "Chelia",
          "Djerma",
          "Fesdis",
          "Ghassira",
          "Hidoussa",
          "Ichmoul",
          "Inoughissen",
          "Kimmel",
          "Larbaa",
          "Menaa",
          "Merouana",
          "N'Gaous",
          "Oued Chaaba",
          "Oued El Ma",
          "Oued Taga",
          "Ouled Ammar",
          "Ouled Sellem",
          "Ouled Si Slimane",
          "Ras El Aioun",
          "Seggana",
          "Sefiane",
          "Seriana",
          "Talkhamt",
          "Taxlent",
          "Teniet El Abed",
          "Tazoult",
          "Tilatou",
          "Timgad",
          "Zanet El Beida"],

  "Béjaïa":["Béjaïa",
          "Amizour",
          "Ferraoun",
          "Taourirt Ighil",
          "Chellata",
          "Tamokra",
          "Timezrit",
          "Souk El Ténine",
          "M'cisna",
          "Tinabdher",
          "Tichy",
          "Semaoun",
          "Kendira",
          "Tifra",
          "Ighram",
          "Amalou",
          "Ighil Ali",
          "Fenaïa Ilmaten",
          "Toudja",
          "Darguina",
          "Sidi-Ayad",
          "Aokas",
          "Beni Djellil",
          "Adekar",
          "Akbou",
          "Seddouk",
          "Tazmalt",
          "Aït-R'zine",
          "Chemini",
          "Souk-Oufella",
          "Taskriout",
          "Tibane",
          "Tala Hamza",
          "Barbacha",
          "Beni Ksila",
          "Ouzellaguen",
          "Bouhamza",
          "Beni Mellikeche",
          "Sidi-Aïch",
          "El Kseur",
          "Melbou",
          "Akfadou",
          "Leflaye",
          "Kherrata",
          "Draâ El-Kaïd",
          "Tamridjet",
          "Aït-Smail",
          "Boukhelifa",
          "Tizi N'Berber",
          "Aït Maouche",
          "Oued Ghir",
          "Boudjellil"
          ],

  "Biskra":["Biskra",
          "El Kantara",
          "Ain Zaatout",
          "Ain Naga",
          "Ain Oulmene",
          "Chetma",
          "El Outaya",
          "Foughala",
          "Lichana",
          "Mekhadma",
          "M'Chouneche",
          "Ourlal",
          "Oumache",
          "Sidi Okba",
          "Tolga",
          "Zeribet El Oued",
          "Lioua",
          "El Haouch",
          "Bordj Ben Azzouz",
          "El Hadjira",
          "Sidi Khaled",
          "El Ghrous",
          "M'Lili",
          "Ouled Djellal",
          "Doucen",
          "Ras El Miad",
          "Ouled Slimane",
          "El Feidh"],

  "Béchar":["Béchar",
            "Abadla",
            "Beni Ounif",
            "Boukais",
            "Erg Ferradj",
            "Kenadsa",
            "Lahmar",
            "Meridja",
            "Mogheul",
            "Taghit",
            "Tamtert",
            "Timmiaouine"],

  "Blida":["Blida",
          "Boufarik",
          "Bouarfa",
          "Beni Tamou",
          "Birkhadem",
          "Chréa",
          "El Affroun",
          "Hammam Melouane",
          "Larbaa",
          "Mouzaia",
          "Oued El Alleug",
          "Ouled Yaïch",
          "Souhane",
          "Beni Mered",
          "Ben Khelil",
          "Meftah"],

  "Bouira":["Bouira",
            "Aïn Bessem",
            "Aïn Turk",
            "Bechloul",
            "Bir Ghbalou",
            "Bordj Okhriss",
            "Boukram",
            "El Hachimia",
            "El Adjiba",
            "El Asnam",
            "El Hakimia",
            "Haizer",
            "Lakhdaria",
            "Les Bibans",
            "M'Chedallah",
            "Oued El Berdi",
            "Ouled Rached",
            "Rafès",
            "Saharidj",
            "Sour El-Ghozlane",
            "Taghzourt",
            "Taguedite",
            "Tebarrayen"],

  "Tamanrasset":["Tamanrasset",
                "Abalessa",
                "In Amguel",
                "In Guezzam",
                "In Salah",
                "Tazrouk"],

  "Tébessa":["Tébessa",
            "Bir El Ater",
            "Negrine",
            "El Aouinet",
            "Morsott",
            "Bir Mokkadem",
            "Ouenza",
            "El Ma Labiod",
            "Guelta Zerka",
            "Boukhadra",
            "Stah Guentis",
            "Saf Saf El Oues",
            "Bedjene",
            "Bekkaria",
            "El Meridj",
            "Hammamet",
            "Oum Ali",
            "Bir Dheb",
            "El Ogla El Malha",
            "Boulhaf Dir",
            "Oued El Aoun",
            "El Kouif",
            "Ferkane"],

  "Tlemcen":["Tlemcen",
            "Ain Fezza",
            "Amieur",
            "Azails",
            "Bab El Assa",
            "Bensekrane",
            "Beni Mester",
            "Beni Oudjene",
            "Beni Snous",
            "Beni Bahdel",
            "Bouhlou",
            "Chetouane",
            "Dar Yaghmara",
            "El Gor",
            "El Bouihi",
            "El Aricha",
            "El Fehoul",
            "El Maleh",
            "Honaine",
            "Maghnia",
            "Mansourah",
            "Marsat Ben M’Hidi",
            "Marsa Ben M’Hidi",
            "Msirda Fouaga",
            "Nedroma",
            "Oued Lakhdar",
            "Ouled Riyah",
            "Remchi",
            "Sabra",
            "Sebdou",
            "Sidi Abdelli",
            "Sidi Djillali",
            "Sidi Medjahed",
            "Souahlia",
            "Souk Tlata",
            "Terny Beni Hediel",
            "Zenata"],

  "Tiaret":[ "Tiaret",
            "Aïn Bouchekif",
            "Aïn Dheb",
            "Aïn El Hadid",
            "Aïn Kermes",
            "Aïn Zarit",
            "Baïr Sidi Amar",
            "Bouheni",
            "Chehaima",
            "Dahmouni",
            "Djouab",
            "Djillali Ben Amar",
            "Faidja",
            "Frenda",
            "Guertoufa",
            "Hamadia",
            "Ksar Chellala",
            "Mahdia",
            "Mechraa Sfa",
            "Medroussa",
            "Meghila",
            "Melakou",
            "Mellakou",
            "Nadorah",
            "Oued Lili",
            "Rahouia",
            "Rechaiga",
            "Sebt",
            "Serghine",
            "Sidi Abderrahmane",
            "Sidi Bakhti",
            "Sidi Hosni",
            "Siouf",
            "Sougueur",
            "Tagdemt",
            "Takhmaret",
            "Terny",
            "Tidda",
            "Tousnina",
            "Zmalet El Emir Abdelkader"],

  "Tizi Ouzou":["Tizi Ouzou",
              "Aghribs",
              "Aïn El Hammam",
              "Aït Aggouacha",
              "Aït Chafâa",
              "Aït Khellili",
              "Aït Mahmoud",
              "Aït Oumalou",
              "Aït-Toudert",
              "Akbil",
              "Akbou",
              "Akerrou",
              "At Ouacif",
              "Aït Yenni",
              "Azeffoun",
              "Azazga",
              "Beni Douala",
              "Beni Zmenzer",
              "Beni Aïssi",
              "Beni Ammar",
              "Beni Yenni",
              "Boghni",
              "Boudjima",
              "Bounouh",
              "Bouzeguène",
              "Draâ Ben Khedda",
              "Draâ El Mizan",
              "Freha",
              "Frikat",
              "Iflissen",
              "Idjeur",
              "Iferhounène",
              "Illilten",
              "Illoula Oumalou",
              "Imsouhal",
              "Irdjen",
              "Larbaa Nath Irathen",
              "Makouda",
              "Mechtras",
              "Mekla",
              "M'Kira",
              "M'Zouda",
              "Ouaguenoun",
              "Ouadhias",
              "Ouacif",
              "Ouaguenoun",
              "Souamaâ",
              "Tadmaït",
              "Tigzirt",
              "Tizi Gheniff",
              "Tizi N'Tleta",
              "Tizi Rached",
              "Voughard",
              "Yatafen",
              "Zekri",
              "Iboudrarène",
              "Idjeur",
              "Assi Youcef",
              "Timizart",
              "Illoula Oumalou",
              "Ouacif",
              "Aït-Toudert",
              "Aït Chafâa",
              "Tizi N'Tleta",
              "Aït Khellili",
              "Aït Mahoud",
              "Aït Oumalou",
              "Aït Aggouacha"],

  "Algiers":["Alger Centre",
              "Sidi M'Hamed",
              "El Madania",
              "Belouizdad",
              "El Mouradia",
              "Hydra",
              "Bir Mourad Raïs",
              "El Magharia",
              "El Harrach",
              "Baraki",
              "Oued Smar",
              "Birkhadem",
              "Bir Mourad Raïs",
              "Birkhadem",
              "El Biar",
              "Bab El Oued",
              "Casbah",
              "Bologhine",
              "Rais Hamidou",
              "Oued Koriche",
              "Diar El Mahçoul",
              "El Hammamet",
              "Kouba",
              "Hussein Dey",
              "Mohammadia",
              "Bordj El Kiffan",
              "Dar El Beïda",
              "Bab Ezzouar",
              "Bordj El Bahri",
              "Bordj El Kiffan",
              "El Marsa",
              "Heuraoua",
              "Ouled Chebel",
              "El Achour",
              "Draria",
              "El Achour",
              "Djasr Kasentina",
              "Sidi Moussa",
              "Aïn Taya",
              "Tessala El Merdja",
              "Marsa",
              "Reghaïa",
              "Rouiba",
              "Baraki",
              "El Harrach",
              "Hasnaoua",
              "Bir Mourad Raïs",
              "Birkhadem",
              "Bir Mourad Raïs",
              "Bir Mourad Raïs",
              "Bir Mourad Raïs"],

  "Djelfa":["Djelfa",
          "Aïn Chouhada",
          "Aïn El Ibel",
          "Birine",
          "Bouira Lahdab",
          "Charef",
          "Dar Chioukh",
          "El Idrissia",
          "El Khemis",
          "Faidh El Botma",
          "Guernini",
          "Guettara",
          "Had Sahary",
          "Hassi Bahbah",
          "Hassi El Euch",
          "Messaâd",
          "Oum Laadham",
          "Sed Rahal",
          "Selmana",
          "Sidi Baizid",
          "Sidi Ladjel",
          "Tadmit",
          "Taadmit",
          "Zaafrane"],

  "Jijel":["Jijel",
          "Taher",
          "El Milia",
          "Sidi Maârouf",
          "Settara",
          "Texenna",
          "El Aouana",
          "Bouraoui Belhadef",
          "Eraguene",
          "Ghebala",
          "Djimla",
          "M'Gharia",
          "Ouled Rabah",
          "Chahna",
          "Beni Ahmed",
          "Beni Belaid",
          "Beni H'bibi",
          "Beni Yadjis",
          "Kaous",
          "Selma Benziada",
          "Ouled Yahia Khadrouch",
          "Ziama Mansouriah",
          "Emir Abdelkader"],

  "Sétif":["Sétif",
          "Ain Abessa",
          "Ain Arnat",
          "Ain Azel",
          "Ain El Kebira",
          "Ain Lahdjar",
          "Ain Oulmene",
          "Ain Roua",
          "Ain Sebt",
          "Ait Naoual Mezraia",
          "Amoucha",
          "Babor",
          "Bazer Sakhra",
          "Beida Bordj",
          "Beni Fouda",
          "Bir El Arch",
          "Bouandas",
          "Bougaâ",
          "Bousselam",
          "Bouti Sayah",
          "Dehamcha",
          "Draa Kebila",
          "El Eulma",
          "El Ouricia",
          "Guellal",
          "Guidjel",
          "Hamma",
          "Harbil",
          "Ksar El Abtal",
          "Maaouia",
          "Mezloug",
          "Oued El Barad",
          "Ouled Addouane",
          "Ouled Saber",
          "Rasfa",
          "Serdj El Ghoul",
          "Tachouda",
          "Tala Ifacene",
          "Taya",
          "Tella",
          "Tizi N'Bechar"],

  "Saïda":["Saïda",
          "Aïn El Hadjar",
          "Aïn Soltane",
          "Doui Thabet",
          "El Hassasna",
          "Moulay Larbi",
          "Ouled Brahim",
          "Ouled Khaled",
          "Sidi Amar",
          "Sidi Boubekeur",
          "Sidi Ahmed",
          "Sidi Slimane",
          "Tircine",
          "Youb"],

  "Skikda":["Skikda",
          "Aïn Bouziane",
          "Aïn Charchar",
          "Azzaba",
          "Beni Bechir",
          "Beni Oulbane",
          "Beni Zid",
          "Bouchet",
          "Collo",
          "El Hadaik",
          "El Harrouch",
          "El Marsa",
          "Emdjez Edchich",
          "Es Sebt",
          "Filfila",
          "Kerkera",
          "Ouldja Boulbil",
          "Oum Toub",
          "Ramdane Djamel",
          "Sidi Mezghiche",
          "Tamalous",
          "Zeramna"
          ],

  "Sidi Bel Abbès":["Sidi Bel Abbès",
                  "Aïn Adden",
                  "Aïn El Berd",
                  "Aïn Kada",
                  "Aïn Tindamine",
                  "Ben Badis",
                  "Benachiba Chelia",
                  "Boukhanefis",
                  "Bowékhane",
                  "Chellal",
                  "Dhaya",
                  "El Hassi",
                  "Hassi Zehroun",
                  "Lamtar",
                  "Marhoum",
                  "Mekerra",
                  "Merine",
                  "Mezaourou",
                  "Mostefa Ben Brahim",
                  "Oued Taourira",
                  "Ras El Ma",
                  "Redjem Demouche",
                  "Sehala",
                  "Sfisifa",
                  "Sidi Ali Benyoub",
                  "Sidi Brahim",
                  "Sidi Chaib",
                  "Sidi Dahou Zairs",
                  "Sidi Hamadouche",
                  "Sidi Khaled",
                  "Tafissour",
                  "Télagh",
                  "Tessala",
                  "Tenira",
                  "Zerouala"
                  ],

  "Annaba":["Annaba",
          "Berrahal",
          "El Bouni",
          "El Hadjar",
          "Oued El Aneb",
          "Aïn El Berda",
          "Seraïdi",
          "Chetaïbi",
          "El Eulma",
          "Treat"
  ],

  "Guelma":["Guelma",
            "Aïn Ben Beida",
            "Aïn larbi",
            "Aïn Makhlouf",
            "Aïn Sandel",
            "Belkheir",
            "Ben Djerrah",
            "Bou Hamdane",
            "Bouchegouf",
            "Dahouara",
            "Djebbala",
            "El Fedjoudj",
            "Guelaat Bou Sbaa",
            "Hamam Debagh",
            "Hammam N’bails",
            "Houari Boumediène",
            "Khezaras",
            "Medjez Sfa",
            "Nechmaya",
            "Oued Ferragha",
            "Oued Zenati",
            "Roknia",
            "Sellaoua Announa"
            ],

  "Constantine":["Constantine",
                "Aïn Abid",
                "Aïn Smara",
                "Ben Badis",
                "Didouche Mourad",
                "El Khroub",
                "Hamma Bouziane",
                "Ibn Ziad",
                "Messaoud Boudjriou",
                "Oued El Had",
                "Zighoud Youcef"],

  "Médéa":["Médéa",
          "Aïn Boucif",
          "Aïn Djemaa",
          "Aïn Ouksir",
          "Aziz",
          "Baata",
          "Beni Slimane",
          "Berrouaghia",
          "Bou Aiche",
          "Bouaichoune",
          "Bouskene",
          "Chahbounia",
          "Chelalet El Adhaoura",
          "Cheniguel",
          "Derrag",
          "Djouab",
          "Dragui",
          "El Azizia",
          "El Guelb El Kebir",
          "El Hamdania",
          "El Omaria",
          "Guelb El Kébir",
          "Ksar El Boukhari",
          "Meghraoua",
          "Mezerana",
          "M'fatha",
          "M'Salah",
          "Ouzera",
          "Ouled Deide",
          "Ouled Hellal",
          "Ouled Maareb",
          "Sedraya",
          "Senhadja",
          "Seghouane",
          "Si Mahdjoub",
          "Sidi Errabia",
          "Sidi Maâmar",
          "Sidi Naâmane",
          "Souaghi",
          "Tablat",
          "Tamesguida",
          "Tizi Mahdi",
          "Zoubiria"],

  "Mostaganem":["Mostaganem",
                "Aïn Nouissy",
                "Aïn Sidi Cherif",
                "Achaacha",
                "Benabdelmalek Ramdane",
                "Bouguirat",
                "Fornaka",
                "Hadjadj",
                "Hassi Mamèche",
                "Khadidja",
                "Kheireddine",
                "Mazagran",
                "Mesra",
                "Nekmaria",
                "Oued El Kheir",
                "Ouled Boughalem",
                "Sayada",
                "Sirat",
                "Souaflia",
                "Sour",
                "Stidia",
                "Tazgait"],

  "M’Sila":["M'Sila",
            "Aïn El Hadjel",
            "Aïn El Melh",
            "Aïn Fares",
            "Aïn Kerman",
            "Belaiba",
            "Ben Srour",
            "Berhoum",
            "Birkhadem",
            "Bordj Ben Zerguine",
            "Bou Saâda",
            "Bousaada",
            "Chellal",
            "Dehahna",
            "Djebel Messaâd",
            "El Houamed",
            "El Khroub",
            "Hammam Dalaa",
            "Khettouti Sed El Djir",
            "Khoubana",
            "Maadid",
            "Magra",
            "M'Cif",
            "Mohamed Boudiaf",
            "Ouled Addi Guebala",
            "Ouled Derradj",
            "Ouled Madhi",
            "Ouled Mansour",
            "Ouled Rahmoun",
            "Oultem",
            "Sidi Aïssa",
            "Sidi Hadjeres",
            "Tamsa",
            "Tarmount",
            "Zarzour"],

  "Mascara":["Mascara",
            "Alaïmia",
            "Aouf",
            "Aouf Sud",
            "Bou Henni",
            "El Gaada",
            "El Ghomri",
            "El Keurt",
            "El Menaouer",
            "El Sfid",
            "Ferraguig",
            "Gharb",
            "Gharbia",
            "Guerouaou",
            "Hacine",
            "Maoussa",
            "Matemore",
            "Mohammadia",
            "Oggaz",
            "Oued Taria",
            "Ras Ain Amirouche",
            "Sedjerara",
            "Sidi Abdeldjebar",
            "Sidi Abdelmoumene",
            "Sidi Boussaid",
            "Sidi Kada",
            "Sig",
            "Tighennif",
            "Zahana"],

  "Ouargla":["Ouargla",
            "Ain Beida",
            "Blidet Amor",
            "El Borma",
            "El Hadjira",
            "Hassi Messaoud",
            "Hassi Ben Abdellah",
            "Megarine",
            "N'Goussa",
            "Rouissat",
            "Sidi Khouiled",
            "Tebesbest",
            "Touggourt"],

  "Oran":["Oran",
        "Aïn Turk",
        "Arzew",
        "Bethioua",
        "Bir El Djir",
        "Boufatis",
        "El Ançor",
        "Es Sénia",
        "Gdyel",
        "Hassi Bounif",
        "Hassi Mefsoukh",
        "Mers El Hadjadj",
        "Oued Tlélat",
        "Sidi Ben Yebka",
        "Sidi Chami",
        "Tafraoui"],
        
  "El Bayadh":["El Bayadh",
              "Arbaouat",
              "Boualem",
              "Bougtoub",
              "Boussemghoun",
              "Brezina",
              "Chellala",
              "El Abiodh Sidi Cheikh",
              "El Bnoud",
              "El Kheiter",
              "Ghassoul",
              "Krakda",
              "Rogassa",
              "Sidi Ameur",
              "Sidi Taifour",
              "Stitten"],

  "Illizi":["Illizi",
            "Debdeb",
            "Bordj Omar Driss",
            "In Amenas"],

  "Bordj Bou Arreridj":["Bordj Bou Arreridj",
                      "Aïn Taghrout",
                      "Aïn Tesra",
                      "Belimour",
                      "Ben Daoud",
                      "Bir Kasdali",
                      "Bordj Ghedir",
                      "Bordj Zemoura",
                      "Colla",
                      "Djaafra",
                      "El Achir",
                      "El Anseur",
                      "El Hamadia",
                      "El Main",
                      "El M'hir",
                      "Ghilassa",
                      "Haraza",
                      "Hasnaoua",
                      "Khelil",
                      "Ksour",
                      "Mansoura",
                      "Medjana",
                      "Ouled Brahem",
                      "Ouled Dahmane",
                      "Ouled Sidi Brahim",
                      "Rabta",
                      "Ras El Oued",
                      "Sidi Embarek",
                      "Tefreg",
                      "Taglait",
                      "Teniet En Nasr",
                      "Tassameurt",
                      "Tixter"],

  "Boumerdès":["Afir",
              "Ammal",
              "Baghlia",
              "Ben Choud",
              "Beni Amrane",
              "Bordj Menaïel",
              "Boudouaou",
              "Boudouaou El Bahri",
              "Boumerdès",
              "Bouzegza Keddara",
              "Chabet El Ameur",
              "Corso",
              "Dellys",
              "Djinet",
              "El Kharrouba",
              "Hammedi",
              "Isser",
              "Khemis El Khechna",
              "Larbatache",
              "Leghata",
              "Naciria",
              "Ouled Aïssa",
              "Ouled Hedadj",
              "Ouled Moussa",
              "Si Mustapha",
              "Sidi Daoud",
              "Souk El Had",
              "Taourga",
              "Thénia",
              "Tidjelabine",
              "Timezrit",
              "Zemmouri"],

  "El Tarf":["Aïn El Assel",
            "Aïn Kerma",
            "Asfour",
            "Ben Mehidi",
            "Berrihane",
            "Besbes",
            "Bougous",
            "Bouhadjar",
            "Bouteldja",
            "Chebaita Mokhtar",
            "Chefia",
            "Chihani",
            "Dréan",
            "Echatt",
            "El Aïoun",
            "El Kala",
            "El Tarf",
            "Hammam Beni Salah",
            "Lac Des Oiseaux",
            "Oued Zitoun",
            "Raml Souk",
            "Souarekh",
            "Zerizer",
            "Zitouna"],

  "Tindouf":["Tindouf",
            "Oum El Assel"],

  "Tissemsilt":[ "Tissemsilt",
                "Ammari",
                "Beni Chaib",
                "Beni Lahcene",
                "Boucaid",
                "Bordj Bou Naama",
                "Bordj El Emir Abdelkader",
                "Khemisti",
                "Larbaa",
                "Lardjem",
                "Layoune",
                "Lazharia",
                "Maacem",
                "Melaab",
                "Ouled Bessem",
                "Sidi Abed",
                "Sidi Boutouchent",
                "Sidi Lantri",
                "Sidi Slimane",
                "Tamellahet",
                "Theniet El Had",
                "Youssoufia"],

  "El Oued":["El Oued",
            "Robbah",
            "Oued El Alenda",
            "Bayadha",
            "Nakhla",
            "Guemar",
            "Kouinine",
            "Reguiba",
            "Hamraia",
            "Taghzout",
            "Debila",
            "Hassani Abdelkrim",
            "Hassi Khalifa",
            "Taleb Larbi",
            "Douar El Ma",
            "Sidi Aoun",
            "Trifaoui",
            "Magrane",
            "Beni Guecha",
            "Ourmas",
            "El Ogla",
            "Mih Ouansa"],

  "Khenchela": ["Khenchela",
                "Babar",
                "Baghai",
                "Chechar",
                "Kais",
                "M'Toussa",
                "El Hamma",
                "Ensigha",
                "Tamza",
                "Aïn Touila",
                "Bouhmama",
                "Yabous",
                "Remia",
                "Taouzient",
                "El Oueldja",
                "Djellal",
                "Ouled Rechache",
                "Boumezou",
                "Khirane",
                "M'Sara",
                "Talaga",
                "Tamsa"],

  "Souk Ahras":["Souk Ahras",
              "Sedrata",
              "Hanancha",
              "Mechroha",
              "Ouled Driss",
              "Tiffech",
              "Zaarouria",
              "Taoura",
              "Dréa",
              "Heddada",
              "Khedara",
              "Merahna",
              "Ouled Moumene",
              "Bir Bou Haouch",
              "M'daourouch",
              "Oum El Adhaim",
              "Aïn Zana",
              "Aïn Soltane",
              "Ouillen",
              "Sidi Fredj",
              "Safel El Ouiden",
              "Ragouba",
              "Khemissa",
              "Oued Keberit",
              "Terraguelt",
              "Zouabi"],

  "Tipaza":["Tipaza",
            "Ahmar El Aïn",
            "Aghbal",
            "Aïn Tagourait",
            "Attatba",
            "Beni Milleuk",
            "Bou Ismaïl",
            "Bouharoun",
            "Bourkika",
            "Chaiba",
            "Cherchell",
            "Damous",
            "Douaouda",
            "Fouka",
            "Gouraya",
            "Hadjeret Ennous",
            "Hadjout",
            "Khemisti",
            "Koléa",
            "Larhat",
            "Menaceur",
            "Merad",
            "Messelmoun",
            "Nador",
            "Sidi Amar",
            "Sidi Ghiles",
            "Sidi Rached",
            "Sidi Semiane"],

  "Mila":["Ahmed Rachedi",
          "Aïn Beida Harriche",
          "Aïn Mellouk",
          "Aïn Tine",
          "Amira Arrès",
          "Benyahia Abderrahmane",
          "Bouhatem",
          "Chelghoum Laïd",
          "Chigara",
          "Derradji Bousselah",
          "El Mechira",
          "Elayadi Barbes",
          "Ferdjioua",
          "Grarem Gouga",
          "Hamala",
          "Mila",
          "Minar Zarza",
          "Oued Athmania",
          "Oued Endja",
          "Oued Seguen",
          "Ouled Khalouf",
          "Rouached",
          "Sidi Khelifa",
          "Sidi Merouane",
          "Tadjenanet",
          "Tassadane Haddada",
          "Teleghma",
          "Terrai Bainen",
          "Tessala Lemtaï",
          "Tiberguent",
          "Yahia Beni Guecha",
          "Zeghaia"],

  "Aïn Defla":["Aïn Benian",
              "Aïn Bouyahia",
              "Aïn Defla",
              "Aïn Lechiekh",
              "Aïn Soltane",
              "Aïn Torki",
              "Arib",
              "Bathia",
              "Belaas",
              "Ben Allal",
              "Birbouche",
              "Bir Ould Khelifa",
              "Bordj Emir Khaled",
              "Boumedfaa",
              "Bourached",
              "Djelida",
              "Djemaa Ouled Cheikh",
              "Djendel",
              "El Abadia",
              "El Amra",
              "El Attaf",
              "El Hassania",
              "El Maine",
              "Hammam Righa",
              "Hoceinia",
              "Khemis Miliana",
              "Mekhatria",
              "Miliana",
              "Oued Chorfa",
              "Oued Djemaa",
              "Rouina",
              "Sidi Lakhdar",
              "Tacheta Zougagha",
              "Tarik Ibn Ziad",
              "Tiberkanine",
              "Zeddine"],

  "Naama":["Naâma",
          "Mécheria",
          "Aïn Sefra",
          "Tiout",
          "Sfissifa",
          "Moghrar",
          "Assela",
          "Djeniene Bourezg",
          "Aïn Ben Khelil",
          "Mekmen Ben Amar",
          "Kasdir",
          "El Biodh"],

  "Aïn Témouchent":["Aghlal",
                  "Aïn El Arbaa",
                  "Aïn Kihal",
                  "Aïn Témouchent",
                  "Aïn Tolba",
                  "Aoubellil",
                  "Beni Saf",
                  "Bouzedjar",
                  "Chaabat El Leham",
                  "Chentouf",
                  "El Amria",
                  "El Emir Abdelkader",
                  "El Malah",
                  "El Messaid",
                  "Hammam Bouhadjar",
                  "Hassasna",
                  "Hassi El Ghella",
                  "Oued Berkeche",
                  "Oued Sebbah",
                  "Ouled Boudjemaa",
                  "Ouled Kihal",
                  "Oulhaça El Gheraba",
                  "Sidi Ben Adda",
                  "Sidi Boumedienne",
                  "Sidi Ouriache",
                  "Sidi Safi",
                  "Tamzoura",
                  "Terga"],

  "Ghardaïa":["Ghardaïa",
            "Berriane",
            "Bounoura",
            "Dhayet Bendhahoua",
            "El Atteuf",
            "El Guerrara",
            "Mansoura",
            "Metlili",
            "Sebseb",
            "Zelfana"],

  "Relizane":["Relizane",
            "Aïn Rahma",
            "Aïn Tarek",
            "Ammi Moussa",
            "Belassel Bouzegza",
            "Bendaoud",
            "Beni Dergoun",
            "Beni Zentis",
            "Dar Ben Abdelah",
            "Djidiouia",
            "El Guettar",
            "El Hassi",
            "El H'Madna",
            "El Matmar",
            "El Ouldja",
            "Had Echkalla",
            "Hamri",
            "Kalaa",
            "Lahlef",
            "Mazouna",
            "Mediouna",
            "Mendes",
            "Merdja Sidi Abed",
            "Oued Djemaâ",
            "Oued Essalem",
            "Oued Rhiou",
            "Ouled Aiche",
            "Ouled Sidi Mihoub",
            "Ramka",
            "Sidi Khettab",
            "Sidi Lazreg",
            "Sidi M'Hamed Ben Ali",
            "Sidi M'Hamed Benaouda",
            "Sidi Saâda",
            "Souk El Had",
            "Yellel",
            "Zemmora"],

  "Timimoun":["Timimoun",
              "Ouled Saïd",
              "Aougrout",
              "Deldoul",
              "Metarfa",
              "Tinerkouk",
              "Ksar Kaddour",
              "Charouine",
              "Ouled Aïssa",
              "Talmine"],

  "Bordj Badji Mokhtar":["Bordj Badji Mokhtar",
                          "Timiaouine"],

  "Ouled Djellal":["Ouled Djellal",
                  "Doucen",
                  "Ech Chaïba",
                  "Sidi Khaled",
                  "Besbes",
                  "Ras El Miaad"],

  "Béni Abbès":["Béni Abbès",
              "Tamtert",
              "Kerzaz",
              "Timoudi",
              "El Ouata",
              "Beni Ikhlef",
              "Tabelbala",
              "Ouled Khoudir",
              "Ksabi",
              "Igli"],

  "In Salah":["In Salah",
            "In Ghar",
            "Foggaret Ezzaouia"],

  "In Guezzam":["In Guezzam",
              "Tin Zaouatine"],

  "Touggourt":["Touggourt",
              "Nezla",
              "Tebesbest",
              "Zaouia El Abidia",
              "El Hadjira",
              "El Allia",
              "Megarine",
              "Sidi Slimane",
              "Benaceur",
              "M'Naguer",
              "Taibet",
              "Blidet Amor",
              "Temacine"],

  "Djanet":["Djanet",
            "Bordj El Houasse"],

  "El M'Ghair":[ "Djamaa",
              "El M'Ghair",
              "Merara",
              "Oum Touyour",
              "Sidi Amrane",
              "Sidi Khellil",
              "Still",
              "Tendla"],

  "El Meniaa":["El Meniaa",
              "Hassi Gara",
              "Hassi Fehal"],

};

