# Generated by Copilot on 2025-12-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="partner",
            old_name="name",
            new_name="company_name",
        ),
        migrations.AddField(
            model_name="partner",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partners",
                to="locations.region",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="listing_address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
