# Generated by Copilot on 2025-12-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_partner_schema_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="partners/logos/"),
        ),
        migrations.AddField(
            model_name="user",
            name="partner",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user",
                to="users.partner",
            ),
        ),
    ]
