# Generated by Copilot on 2026-01-01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_activation_otp"),
        ("users", "0003_user_partner_link"),
    ]

    operations = []
