# Generated by Django 5.2.8 on 2025-12-01 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("interactions", "0001_initial"),
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="listings.listing",
            ),
        ),
    ]
