# Generated by Django 5.2.8 on 2026-01-07 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0003_initial"),
        ("listings", "0006_alter_listingdocument_file_nullable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["user", "listing"], name="interaction_user_id_13f760_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["user", "created_at"], name="interaction_user_id_718974_idx"
            ),
        ),
    ]
